### PR TITLE
Fix Uploading Profiles

### LINKED ISSUE #1066: [BUG] Profile File Save is failing
**Describe the bug**
It currently is not possible to save a profile to the database in server mode.

**To Reproduce**
1. Load a profile (for example https://github.com/mitre/inspec_tools/blob/master/examples/sample_json/single_control_profile.json)
2. Click on the sidebar
3. Click on save
4. See error on console and see no saved file.

### PR DESCRIPTION
**Pull request by camdenmoors**
Closes #1066, adds detection for profile files to SidebarFileList to fix uploading of profiles.

### CODE REVIEW

File: apps/frontend/src/components/global/sidebaritems/SidebarFileList.vue [hunk 1]
```diff
@@ -76,8 +76,8 @@ export default class FileItem extends mixins(ServerMixin) {
       SnackbarModule.failure('This evaluation is already in the database.')
```
Comment (Bialogs) [inline apps/frontend/src/components/global/sidebaritems/SidebarFileList.vue]:
```suggestion
      SnackbarModule.failure('This file is already in the database.')
```

**Review by Bialogs — APPROVED** [review]
